# Generated by Django 5.2.4 on 2025-07-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='proce',
            new_name='price',
        ),
    ]
